# Generated by Django 5.2.1 on 2025-06-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField()),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='AccAdverbio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.forma')),
                ('gradacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.accauxgradacion')),
            ],
            options={
                'verbose_name': 'Acentuación Adverbio',
                'verbose_name_plural': 'Acentuaciones Adverbios',
                'unique_together': {('forma', 'gradacion')},
            },
        ),
        migrations.CreateModel(
            name='AccSignificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.forma')),
                ('significado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.significados')),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.textos')),
            ],
            options={
                'verbose_name': 'Acentuación Significado',
                'verbose_name_plural': 'Acentuaciones Significados',
                'unique_together': {('significado', 'forma', 'texto')},
            },
        ),
        migrations.CreateModel(
            name='AccSustantivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.accauxcasus')),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.forma')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.accauxgeneros')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.accauxnum')),
            ],
            options={
                'verbose_name': 'Acentuación Sustantivo',
                'verbose_name_plural': 'Acentuaciones Sustantivos',
                'unique_together': {('forma', 'genero', 'caso', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='AccVerbo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lexicon.accauxcasus')),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.forma')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lexicon.accauxgeneros')),
                ('gradacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lexicon.accauxgradacion')),
                ('numero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lexicon.accauxnum')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lexicon.accauxpersona')),
            ],
            options={
                'verbose_name': 'Acentuación Verbo',
                'verbose_name_plural': 'Acentuaciones Verbos',
                'unique_together': {('forma', 'genero', 'caso', 'numero', 'gradacion', 'persona')},
            },
        ),
        migrations.CreateModel(
            name='AccVerboFnom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.accauxcasus')),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.forma')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.accauxgeneros')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.accauxnum')),
            ],
            options={
                'verbose_name': 'Acentuación Verbo F. No Personal',
                'verbose_name_plural': 'Acentuaciones Verbos F. No Personales',
                'unique_together': {('forma', 'caso', 'genero', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='AuxSignificadosBibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(blank=True, max_length=10, null=True)),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.bibliografia')),
                ('significado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.significados')),
            ],
            options={
                'verbose_name': 'Significado en Bibliografía',
                'verbose_name_plural': 'Significados en Bibliografía',
                'unique_together': {('significado', 'bibliografia')},
            },
        ),
        migrations.CreateModel(
            name='LemBibNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lem_bib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.lemasbibliografia')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.notas')),
            ],
            options={
                'verbose_name': 'Nota de Lema-Bibliografía',
                'verbose_name_plural': 'Notas de Lema-Bibliografía',
                'unique_together': {('lem_bib', 'nota')},
            },
        ),
        migrations.CreateModel(
            name='TxtBibNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.notas')),
                ('txt_bib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.textobibliografia')),
            ],
            options={
                'verbose_name': 'Nota de Texto-Bibliografía',
                'verbose_name_plural': 'Notas de Texto-Bibliografía',
                'unique_together': {('nota', 'txt_bib')},
            },
        ),
    ]
